In [11]:
import skvideo.io
import numpy as np
import scipy as sp

video = np.array(skvideo.io.vread("simple_shape.png"))

print(video.shape)

(3, 240, 240, 3)


In [23]:
print(video)

[[[[255 255 255]
   [254 254 254]
   [254 254 254]
   ...
   [254 254 254]
   [254 254 254]
   [254 254 254]]

  [[254 254 254]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [254 254 254]
   [254 254 254]
   ...
   [254 254 254]
   [254 254 254]
   [254 254 254]]

  ...

  [[255 255 255]
   [254 254 254]
   [254 254 254]
   ...
   [254 254 254]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [254 254 254]
   [254 254 254]
   ...
   [253 253 254]
   [253 253 254]
   [255 255 255]]

  [[254 254 254]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[255 255 255]
   [254 254 254]
   [254 254 254]
   ...
   [255 255 255]
   [254 254 254]
   [254 254 254]]

  [[254 254 254]
   [255 255 255]
   [255 255 255]
   ...
   [254 254 254]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [254 254 254]
   [254 254 254]
   ...
   [255 255 255]
   [254 254 254]
   [254 254

In [30]:
newvideo = np.zeros((3, 16, 16, 3))

#LPF by averaging in order to prevent aliasing

for f in range(3):
    i = 0
    j = 0
    while i < 240:
        while j < 240:
            color0tot = 0
            color1tot = 0
            color2tot = 0
            for k in range(15):
                for l in range(15):
                    color0tot += video[f][i+l][j+k][0]
                    color1tot += video[f][i+l][j+k][1]
                    color1tot += video[f][i+l][j+k][2]
            newvideo[f][i//15][j//15][0] = color0tot // 225.0
            newvideo[f][i//15][j//15][1] = color1tot // 225.0
            newvideo[f][i//15][j//15][2] = color2tot // 225.0
            print((newvideo[f][i//15][j//15][0], newvideo[f][i//15][j//15][1], newvideo[f][i//15][j//15][1]))
            j += 15
        i += 15
            
            


(254.0, 509.0, 509.0)
(254.0, 508.0, 508.0)
(253.0, 508.0, 508.0)
(253.0, 507.0, 507.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(253.0, 507.0, 507.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 509.0, 509.0)
(254.0, 509.0, 509.0)
(254.0, 508.0, 508.0)
(235.0, 472.0, 472.0)
(238.0, 478.0, 478.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(222.0, 445.0, 445.0)
(253.0, 506.0, 506.0)
(253.0, 507.0, 507.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 509.0, 509.0)
(254.0, 509.0, 509.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(253.0, 507.0, 507.0)
(254.0, 508.0, 508.0)
(254.0, 509.0, 509.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 508.0, 508.0)
(254.0, 50

In [26]:
print(newvideo.shape)

(3, 16, 16, 3)
